
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://calebaren.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Caleb Ren"
title: "{ calebaren }"
description: "Portfolio and website of calebaren."
keywords: "caleb, ren, calebaren, github, tech, statistics, computer-science, cs, data"
favicon: "/img/favicon-16.ico"

################
# Header layout #
################

black-favicon: "" # remember to add something here

background-img: "../img/intro-bg.jpg"
body-img: "../img/body-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "// statistician"
  - text: "// computer_scientist"
  # - text: "// dimension_reducer"
  # - text: "// r_programmer"
  # - text: "// python_programmer"
  - text: "// sony_alpha_photographer"
  # - text: "// music_director"
  # - text: "// data_driven"
  # - text: "// graphic_designer"
  # - text: "// product_manager"
  # - text: "// swiss_army_knife"
  # - text: "// data_scientist"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

me-img: "https://graph.facebook.com/100001726448577/picture?type=large&width=500&height=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon_36p.png"
icon-48p: "/img/web-app/icon_48p.png"
icon-72p: "/img/web-app/icon_72p.png"
icon-96p: "/img/web-app/icon_96p.png"
icon-144p: "/img/web-app/icon_144p.png"
icon-192p: "/img/web-app/icon_192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 100

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/stat185.png"
    date: "December 2019"
    description: "Spherelets"
    url: "/stat185_term_paper"
  - image: "/img/timeline/stat139.png"
    date: "October 2019"
    description: "Drugs and Jobs: Unemployment and Overdose Deaths"
    url: "/stat139_project"
  - image: "/img/timeline/cs50.png"
    date: "December 2018"
    description: "That's A Mood"
    url: "/projects/2018/12/24/thats-a-mood.html"

# First image of the Timeline

timeline-img: "/img/timeline/start.jpg"
timeline-url: "https://instagram.com/calebaren"

###########
# Contact #
###########

email: "calebaren@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Caleb Ren is a third-year Harvard College student concentrating in statistics and computer science. He makes a mean mac and cheese."
author_blurb_image: "https://graph.facebook.com/100001726448577/picture?type=large&width=500&height=500"

##################
# Social Buttons #
##################

social:
  # - title: "facebook"
  #   url: "https://facebook.com/calebaren"
  - title: "instagram"
    url: "https://instagram.com/calebaren"
  # - title: "twitter"
  #   url: "https://twitter.com/caleb_aren"
  - title: "github"
    url: "https://github.com/calebaren"
  - title: "linkedin"
    url: "https://linkedin.com/in/calebaren"
  - title: "envelope"
    url: "mailto:calebaren@gmail.com"

############
# 404 page #
############

err-404-img: ""

##################
# GPG on Keybase #
##################

keybase-username: ""
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Resume: 'resume'
  Projects: 'projects'
  Blog: 'latest-post'
  Contact: 'contact'


# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
