# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Caleb Ren
title: Caleb Ren
email: calebaren@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Harvard student studying statistics, data science and computer science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# =========================
# ***** user accounts *****
# =========================
twitter: 
  username: caleb_aren
  url: https://twitter.com/caleb_aren/
github: 
  username: calebaren
  url: https://github.com/calebaren/
facebook:
  username: calebaren
  url: https://www.facebook.com/calebaren/
instagram:
  username: calebaren
  url: https://www.instagram.com/calebaren/
pinterest:
  username: calebaren
  url: https://www.pinterest.com/calebaren/
linkedin:
  username: calebaren
  url: https://www.linkedin.com/in/calebaren/
# ======= Personal Info ========
phone: (206) 849-5804
address: |
  232 Pforzheimer House<br />
  Cambridge, MA 02138
pages_list: # to change
  - index

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
